builders:
  json_locale_builder:
    import: "package:json_model_gen/builder.dart"
    builder_factories: ["jsonLocaleBuilder"]
    build_extensions:
      {"^assets/lang{{}}.json": ["lib/generated/{{}}.dart"]}
    auto_apply: root_package
    build_to: source

targets:
  $default:
    builders:
      json_model_gen|json_locale_builder:
        generate_for:
          - assets/lang/*.json
